set -g mouse on

# Fix vim colorscheme problem in xterminal
set -g default-terminal "xterm-256color"

# Enable vi mode-keys in copy mode
setw -g mode-keys vi

# Set pane history limit to a higher value
set -g history-limit 9999

###############################################################################
################################PLUGINS########################################
# Plugin for copying to system clipboard. Works on MacOS, Linux and Cygwin.
set -g @plugin 'tmux-plugins/tmux-yank'

# Plugin for using vim keybind to navigate through tmux panes
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
